#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class dc_databankDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblBijlage(tblBijlage instance);
  partial void UpdatetblBijlage(tblBijlage instance);
  partial void DeletetblBijlage(tblBijlage instance);
  partial void InserttblVak(tblVak instance);
  partial void UpdatetblVak(tblVak instance);
  partial void DeletetblVak(tblVak instance);
  partial void InserttblDocent(tblDocent instance);
  partial void UpdatetblDocent(tblDocent instance);
  partial void DeletetblDocent(tblDocent instance);
  partial void InserttblDocentVak(tblDocentVak instance);
  partial void UpdatetblDocentVak(tblDocentVak instance);
  partial void DeletetblDocentVak(tblDocentVak instance);
  partial void InserttblEvk(tblEvk instance);
  partial void UpdatetblEvk(tblEvk instance);
  partial void DeletetblEvk(tblEvk instance);
  partial void InserttblExternVak(tblExternVak instance);
  partial void UpdatetblExternVak(tblExternVak instance);
  partial void DeletetblExternVak(tblExternVak instance);
  partial void InserttblOpleiding(tblOpleiding instance);
  partial void UpdatetblOpleiding(tblOpleiding instance);
  partial void DeletetblOpleiding(tblOpleiding instance);
  partial void InserttblOpleidingVak(tblOpleidingVak instance);
  partial void UpdatetblOpleidingVak(tblOpleidingVak instance);
  partial void DeletetblOpleidingVak(tblOpleidingVak instance);
  partial void InserttblStudent(tblStudent instance);
  partial void UpdatetblStudent(tblStudent instance);
  partial void DeletetblStudent(tblStudent instance);
  #endregion
	
	public dc_databankDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dc_databankDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dc_databankDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dc_databankDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dc_databankDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblBijlage> tblBijlages
	{
		get
		{
			return this.GetTable<tblBijlage>();
		}
	}
	
	public System.Data.Linq.Table<tblVak> tblVaks
	{
		get
		{
			return this.GetTable<tblVak>();
		}
	}
	
	public System.Data.Linq.Table<tblDocent> tblDocents
	{
		get
		{
			return this.GetTable<tblDocent>();
		}
	}
	
	public System.Data.Linq.Table<tblDocentVak> tblDocentVaks
	{
		get
		{
			return this.GetTable<tblDocentVak>();
		}
	}
	
	public System.Data.Linq.Table<tblEvk> tblEvks
	{
		get
		{
			return this.GetTable<tblEvk>();
		}
	}
	
	public System.Data.Linq.Table<tblExternVak> tblExternVaks
	{
		get
		{
			return this.GetTable<tblExternVak>();
		}
	}
	
	public System.Data.Linq.Table<tblOpleiding> tblOpleidings
	{
		get
		{
			return this.GetTable<tblOpleiding>();
		}
	}
	
	public System.Data.Linq.Table<tblOpleidingVak> tblOpleidingVaks
	{
		get
		{
			return this.GetTable<tblOpleidingVak>();
		}
	}
	
	public System.Data.Linq.Table<tblStudent> tblStudents
	{
		get
		{
			return this.GetTable<tblStudent>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBijlage")]
public partial class tblBijlage : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_bijlageID;
	
	private string _bijlageURL;
	
	private string _bijlageTitel;
	
	private string _bijlageType;
	
	private int _fk_externvakID;
	
	private EntityRef<tblExternVak> _tblExternVak;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_bijlageIDChanging(int value);
    partial void Onpk_bijlageIDChanged();
    partial void OnbijlageURLChanging(string value);
    partial void OnbijlageURLChanged();
    partial void OnbijlageTitelChanging(string value);
    partial void OnbijlageTitelChanged();
    partial void OnbijlageTypeChanging(string value);
    partial void OnbijlageTypeChanged();
    partial void Onfk_externvakIDChanging(int value);
    partial void Onfk_externvakIDChanged();
    #endregion
	
	public tblBijlage()
	{
		this._tblExternVak = default(EntityRef<tblExternVak>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_bijlageID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_bijlageID
	{
		get
		{
			return this._pk_bijlageID;
		}
		set
		{
			if ((this._pk_bijlageID != value))
			{
				this.Onpk_bijlageIDChanging(value);
				this.SendPropertyChanging();
				this._pk_bijlageID = value;
				this.SendPropertyChanged("pk_bijlageID");
				this.Onpk_bijlageIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bijlageURL", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string bijlageURL
	{
		get
		{
			return this._bijlageURL;
		}
		set
		{
			if ((this._bijlageURL != value))
			{
				this.OnbijlageURLChanging(value);
				this.SendPropertyChanging();
				this._bijlageURL = value;
				this.SendPropertyChanged("bijlageURL");
				this.OnbijlageURLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bijlageTitel", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string bijlageTitel
	{
		get
		{
			return this._bijlageTitel;
		}
		set
		{
			if ((this._bijlageTitel != value))
			{
				this.OnbijlageTitelChanging(value);
				this.SendPropertyChanging();
				this._bijlageTitel = value;
				this.SendPropertyChanged("bijlageTitel");
				this.OnbijlageTitelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bijlageType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string bijlageType
	{
		get
		{
			return this._bijlageType;
		}
		set
		{
			if ((this._bijlageType != value))
			{
				this.OnbijlageTypeChanging(value);
				this.SendPropertyChanging();
				this._bijlageType = value;
				this.SendPropertyChanged("bijlageType");
				this.OnbijlageTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_externvakID", DbType="Int NOT NULL")]
	public int fk_externvakID
	{
		get
		{
			return this._fk_externvakID;
		}
		set
		{
			if ((this._fk_externvakID != value))
			{
				if (this._tblExternVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_externvakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_externvakID = value;
				this.SendPropertyChanged("fk_externvakID");
				this.Onfk_externvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblExternVak_tblBijlage", Storage="_tblExternVak", ThisKey="fk_externvakID", OtherKey="pk_externvakID", IsForeignKey=true)]
	public tblExternVak tblExternVak
	{
		get
		{
			return this._tblExternVak.Entity;
		}
		set
		{
			tblExternVak previousValue = this._tblExternVak.Entity;
			if (((previousValue != value) 
						|| (this._tblExternVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblExternVak.Entity = null;
					previousValue.tblBijlages.Remove(this);
				}
				this._tblExternVak.Entity = value;
				if ((value != null))
				{
					value.tblBijlages.Add(this);
					this._fk_externvakID = value.pk_externvakID;
				}
				else
				{
					this._fk_externvakID = default(int);
				}
				this.SendPropertyChanged("tblExternVak");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVak")]
public partial class tblVak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_vakID;
	
	private string _vakNaam;
	
	private int _vakStudiepunten;
	
	private EntitySet<tblDocentVak> _tblDocentVaks;
	
	private EntitySet<tblEvk> _tblEvks;
	
	private EntitySet<tblOpleidingVak> _tblOpleidingVaks;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_vakIDChanging(int value);
    partial void Onpk_vakIDChanged();
    partial void OnvakNaamChanging(string value);
    partial void OnvakNaamChanged();
    partial void OnvakStudiepuntenChanging(int value);
    partial void OnvakStudiepuntenChanged();
    #endregion
	
	public tblVak()
	{
		this._tblDocentVaks = new EntitySet<tblDocentVak>(new Action<tblDocentVak>(this.attach_tblDocentVaks), new Action<tblDocentVak>(this.detach_tblDocentVaks));
		this._tblEvks = new EntitySet<tblEvk>(new Action<tblEvk>(this.attach_tblEvks), new Action<tblEvk>(this.detach_tblEvks));
		this._tblOpleidingVaks = new EntitySet<tblOpleidingVak>(new Action<tblOpleidingVak>(this.attach_tblOpleidingVaks), new Action<tblOpleidingVak>(this.detach_tblOpleidingVaks));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_vakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_vakID
	{
		get
		{
			return this._pk_vakID;
		}
		set
		{
			if ((this._pk_vakID != value))
			{
				this.Onpk_vakIDChanging(value);
				this.SendPropertyChanging();
				this._pk_vakID = value;
				this.SendPropertyChanged("pk_vakID");
				this.Onpk_vakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vakNaam", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vakNaam
	{
		get
		{
			return this._vakNaam;
		}
		set
		{
			if ((this._vakNaam != value))
			{
				this.OnvakNaamChanging(value);
				this.SendPropertyChanging();
				this._vakNaam = value;
				this.SendPropertyChanged("vakNaam");
				this.OnvakNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vakStudiepunten", DbType="Int NOT NULL")]
	public int vakStudiepunten
	{
		get
		{
			return this._vakStudiepunten;
		}
		set
		{
			if ((this._vakStudiepunten != value))
			{
				this.OnvakStudiepuntenChanging(value);
				this.SendPropertyChanging();
				this._vakStudiepunten = value;
				this.SendPropertyChanged("vakStudiepunten");
				this.OnvakStudiepuntenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblDocentVak", Storage="_tblDocentVaks", ThisKey="pk_vakID", OtherKey="fk_vakID")]
	public EntitySet<tblDocentVak> tblDocentVaks
	{
		get
		{
			return this._tblDocentVaks;
		}
		set
		{
			this._tblDocentVaks.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblEvk", Storage="_tblEvks", ThisKey="pk_vakID", OtherKey="fk_vakID")]
	public EntitySet<tblEvk> tblEvks
	{
		get
		{
			return this._tblEvks;
		}
		set
		{
			this._tblEvks.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblOpleidingVak", Storage="_tblOpleidingVaks", ThisKey="pk_vakID", OtherKey="fk_vakID")]
	public EntitySet<tblOpleidingVak> tblOpleidingVaks
	{
		get
		{
			return this._tblOpleidingVaks;
		}
		set
		{
			this._tblOpleidingVaks.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblDocentVaks(tblDocentVak entity)
	{
		this.SendPropertyChanging();
		entity.tblVak = this;
	}
	
	private void detach_tblDocentVaks(tblDocentVak entity)
	{
		this.SendPropertyChanging();
		entity.tblVak = null;
	}
	
	private void attach_tblEvks(tblEvk entity)
	{
		this.SendPropertyChanging();
		entity.tblVak = this;
	}
	
	private void detach_tblEvks(tblEvk entity)
	{
		this.SendPropertyChanging();
		entity.tblVak = null;
	}
	
	private void attach_tblOpleidingVaks(tblOpleidingVak entity)
	{
		this.SendPropertyChanging();
		entity.tblVak = this;
	}
	
	private void detach_tblOpleidingVaks(tblOpleidingVak entity)
	{
		this.SendPropertyChanging();
		entity.tblVak = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDocent")]
public partial class tblDocent : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_docentID;
	
	private string _docentNaam;
	
	private string _docentWachtwoord;
	
	private double _docentAdmin;
	
	private EntitySet<tblDocentVak> _tblDocentVaks;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_docentIDChanging(int value);
    partial void Onpk_docentIDChanged();
    partial void OndocentNaamChanging(string value);
    partial void OndocentNaamChanged();
    partial void OndocentWachtwoordChanging(string value);
    partial void OndocentWachtwoordChanged();
    partial void OndocentAdminChanging(double value);
    partial void OndocentAdminChanged();
    #endregion
	
	public tblDocent()
	{
		this._tblDocentVaks = new EntitySet<tblDocentVak>(new Action<tblDocentVak>(this.attach_tblDocentVaks), new Action<tblDocentVak>(this.detach_tblDocentVaks));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_docentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_docentID
	{
		get
		{
			return this._pk_docentID;
		}
		set
		{
			if ((this._pk_docentID != value))
			{
				this.Onpk_docentIDChanging(value);
				this.SendPropertyChanging();
				this._pk_docentID = value;
				this.SendPropertyChanged("pk_docentID");
				this.Onpk_docentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docentNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string docentNaam
	{
		get
		{
			return this._docentNaam;
		}
		set
		{
			if ((this._docentNaam != value))
			{
				this.OndocentNaamChanging(value);
				this.SendPropertyChanging();
				this._docentNaam = value;
				this.SendPropertyChanged("docentNaam");
				this.OndocentNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docentWachtwoord", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string docentWachtwoord
	{
		get
		{
			return this._docentWachtwoord;
		}
		set
		{
			if ((this._docentWachtwoord != value))
			{
				this.OndocentWachtwoordChanging(value);
				this.SendPropertyChanging();
				this._docentWachtwoord = value;
				this.SendPropertyChanged("docentWachtwoord");
				this.OndocentWachtwoordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docentAdmin", DbType="Float NOT NULL")]
	public double docentAdmin
	{
		get
		{
			return this._docentAdmin;
		}
		set
		{
			if ((this._docentAdmin != value))
			{
				this.OndocentAdminChanging(value);
				this.SendPropertyChanging();
				this._docentAdmin = value;
				this.SendPropertyChanged("docentAdmin");
				this.OndocentAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDocent_tblDocentVak", Storage="_tblDocentVaks", ThisKey="pk_docentID", OtherKey="fk_docentID")]
	public EntitySet<tblDocentVak> tblDocentVaks
	{
		get
		{
			return this._tblDocentVaks;
		}
		set
		{
			this._tblDocentVaks.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblDocentVaks(tblDocentVak entity)
	{
		this.SendPropertyChanging();
		entity.tblDocent = this;
	}
	
	private void detach_tblDocentVaks(tblDocentVak entity)
	{
		this.SendPropertyChanging();
		entity.tblDocent = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDocentVak")]
public partial class tblDocentVak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_docentvakID;
	
	private int _fk_vakID;
	
	private int _fk_docentID;
	
	private EntityRef<tblDocent> _tblDocent;
	
	private EntityRef<tblVak> _tblVak;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_docentvakIDChanging(int value);
    partial void Onpk_docentvakIDChanged();
    partial void Onfk_vakIDChanging(int value);
    partial void Onfk_vakIDChanged();
    partial void Onfk_docentIDChanging(int value);
    partial void Onfk_docentIDChanged();
    #endregion
	
	public tblDocentVak()
	{
		this._tblDocent = default(EntityRef<tblDocent>);
		this._tblVak = default(EntityRef<tblVak>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_docentvakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_docentvakID
	{
		get
		{
			return this._pk_docentvakID;
		}
		set
		{
			if ((this._pk_docentvakID != value))
			{
				this.Onpk_docentvakIDChanging(value);
				this.SendPropertyChanging();
				this._pk_docentvakID = value;
				this.SendPropertyChanged("pk_docentvakID");
				this.Onpk_docentvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vakID", DbType="Int NOT NULL")]
	public int fk_vakID
	{
		get
		{
			return this._fk_vakID;
		}
		set
		{
			if ((this._fk_vakID != value))
			{
				if (this._tblVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vakID = value;
				this.SendPropertyChanged("fk_vakID");
				this.Onfk_vakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_docentID", DbType="Int NOT NULL")]
	public int fk_docentID
	{
		get
		{
			return this._fk_docentID;
		}
		set
		{
			if ((this._fk_docentID != value))
			{
				if (this._tblDocent.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_docentIDChanging(value);
				this.SendPropertyChanging();
				this._fk_docentID = value;
				this.SendPropertyChanged("fk_docentID");
				this.Onfk_docentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDocent_tblDocentVak", Storage="_tblDocent", ThisKey="fk_docentID", OtherKey="pk_docentID", IsForeignKey=true)]
	public tblDocent tblDocent
	{
		get
		{
			return this._tblDocent.Entity;
		}
		set
		{
			tblDocent previousValue = this._tblDocent.Entity;
			if (((previousValue != value) 
						|| (this._tblDocent.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblDocent.Entity = null;
					previousValue.tblDocentVaks.Remove(this);
				}
				this._tblDocent.Entity = value;
				if ((value != null))
				{
					value.tblDocentVaks.Add(this);
					this._fk_docentID = value.pk_docentID;
				}
				else
				{
					this._fk_docentID = default(int);
				}
				this.SendPropertyChanged("tblDocent");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblDocentVak", Storage="_tblVak", ThisKey="fk_vakID", OtherKey="pk_vakID", IsForeignKey=true)]
	public tblVak tblVak
	{
		get
		{
			return this._tblVak.Entity;
		}
		set
		{
			tblVak previousValue = this._tblVak.Entity;
			if (((previousValue != value) 
						|| (this._tblVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVak.Entity = null;
					previousValue.tblDocentVaks.Remove(this);
				}
				this._tblVak.Entity = value;
				if ((value != null))
				{
					value.tblDocentVaks.Add(this);
					this._fk_vakID = value.pk_vakID;
				}
				else
				{
					this._fk_vakID = default(int);
				}
				this.SendPropertyChanged("tblVak");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEvk")]
public partial class tblEvk : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_evkID;
	
	private int _fk_studentID;
	
	private int _fk_vakID;
	
	private int _fk_externvakID;
	
	private double _evkDocentGoedgekeurd;
	
	private double _evkAdminGoedgekeurd;
	
	private EntityRef<tblVak> _tblVak;
	
	private EntityRef<tblExternVak> _tblExternVak;
	
	private EntityRef<tblStudent> _tblStudent;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_evkIDChanging(int value);
    partial void Onpk_evkIDChanged();
    partial void Onfk_studentIDChanging(int value);
    partial void Onfk_studentIDChanged();
    partial void Onfk_vakIDChanging(int value);
    partial void Onfk_vakIDChanged();
    partial void Onfk_externvakIDChanging(int value);
    partial void Onfk_externvakIDChanged();
    partial void OnevkDocentGoedgekeurdChanging(double value);
    partial void OnevkDocentGoedgekeurdChanged();
    partial void OnevkAdminGoedgekeurdChanging(double value);
    partial void OnevkAdminGoedgekeurdChanged();
    #endregion
	
	public tblEvk()
	{
		this._tblVak = default(EntityRef<tblVak>);
		this._tblExternVak = default(EntityRef<tblExternVak>);
		this._tblStudent = default(EntityRef<tblStudent>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_evkID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_evkID
	{
		get
		{
			return this._pk_evkID;
		}
		set
		{
			if ((this._pk_evkID != value))
			{
				this.Onpk_evkIDChanging(value);
				this.SendPropertyChanging();
				this._pk_evkID = value;
				this.SendPropertyChanged("pk_evkID");
				this.Onpk_evkIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_studentID", DbType="Int NOT NULL")]
	public int fk_studentID
	{
		get
		{
			return this._fk_studentID;
		}
		set
		{
			if ((this._fk_studentID != value))
			{
				if (this._tblStudent.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_studentIDChanging(value);
				this.SendPropertyChanging();
				this._fk_studentID = value;
				this.SendPropertyChanged("fk_studentID");
				this.Onfk_studentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vakID", DbType="Int NOT NULL")]
	public int fk_vakID
	{
		get
		{
			return this._fk_vakID;
		}
		set
		{
			if ((this._fk_vakID != value))
			{
				if (this._tblVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vakID = value;
				this.SendPropertyChanged("fk_vakID");
				this.Onfk_vakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_externvakID", DbType="Int NOT NULL")]
	public int fk_externvakID
	{
		get
		{
			return this._fk_externvakID;
		}
		set
		{
			if ((this._fk_externvakID != value))
			{
				if (this._tblExternVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_externvakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_externvakID = value;
				this.SendPropertyChanged("fk_externvakID");
				this.Onfk_externvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evkDocentGoedgekeurd", DbType="Float NOT NULL")]
	public double evkDocentGoedgekeurd
	{
		get
		{
			return this._evkDocentGoedgekeurd;
		}
		set
		{
			if ((this._evkDocentGoedgekeurd != value))
			{
				this.OnevkDocentGoedgekeurdChanging(value);
				this.SendPropertyChanging();
				this._evkDocentGoedgekeurd = value;
				this.SendPropertyChanged("evkDocentGoedgekeurd");
				this.OnevkDocentGoedgekeurdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evkAdminGoedgekeurd", DbType="Float NOT NULL")]
	public double evkAdminGoedgekeurd
	{
		get
		{
			return this._evkAdminGoedgekeurd;
		}
		set
		{
			if ((this._evkAdminGoedgekeurd != value))
			{
				this.OnevkAdminGoedgekeurdChanging(value);
				this.SendPropertyChanging();
				this._evkAdminGoedgekeurd = value;
				this.SendPropertyChanged("evkAdminGoedgekeurd");
				this.OnevkAdminGoedgekeurdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblEvk", Storage="_tblVak", ThisKey="fk_vakID", OtherKey="pk_vakID", IsForeignKey=true)]
	public tblVak tblVak
	{
		get
		{
			return this._tblVak.Entity;
		}
		set
		{
			tblVak previousValue = this._tblVak.Entity;
			if (((previousValue != value) 
						|| (this._tblVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVak.Entity = null;
					previousValue.tblEvks.Remove(this);
				}
				this._tblVak.Entity = value;
				if ((value != null))
				{
					value.tblEvks.Add(this);
					this._fk_vakID = value.pk_vakID;
				}
				else
				{
					this._fk_vakID = default(int);
				}
				this.SendPropertyChanged("tblVak");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblExternVak_tblEvk", Storage="_tblExternVak", ThisKey="fk_externvakID", OtherKey="pk_externvakID", IsForeignKey=true)]
	public tblExternVak tblExternVak
	{
		get
		{
			return this._tblExternVak.Entity;
		}
		set
		{
			tblExternVak previousValue = this._tblExternVak.Entity;
			if (((previousValue != value) 
						|| (this._tblExternVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblExternVak.Entity = null;
					previousValue.tblEvks.Remove(this);
				}
				this._tblExternVak.Entity = value;
				if ((value != null))
				{
					value.tblEvks.Add(this);
					this._fk_externvakID = value.pk_externvakID;
				}
				else
				{
					this._fk_externvakID = default(int);
				}
				this.SendPropertyChanged("tblExternVak");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblEvk", Storage="_tblStudent", ThisKey="fk_studentID", OtherKey="pk_studentID", IsForeignKey=true)]
	public tblStudent tblStudent
	{
		get
		{
			return this._tblStudent.Entity;
		}
		set
		{
			tblStudent previousValue = this._tblStudent.Entity;
			if (((previousValue != value) 
						|| (this._tblStudent.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblStudent.Entity = null;
					previousValue.tblEvks.Remove(this);
				}
				this._tblStudent.Entity = value;
				if ((value != null))
				{
					value.tblEvks.Add(this);
					this._fk_studentID = value.pk_studentID;
				}
				else
				{
					this._fk_studentID = default(int);
				}
				this.SendPropertyChanged("tblStudent");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblExternVak")]
public partial class tblExternVak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_externvakID;
	
	private string _externvakNaam;
	
	private string _externvakStudiepunt;
	
	private string _externvakJaar;
	
	private string _externvakOpleiding;
	
	private string _externvakSchool;
	
	private EntitySet<tblBijlage> _tblBijlages;
	
	private EntitySet<tblEvk> _tblEvks;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_externvakIDChanging(int value);
    partial void Onpk_externvakIDChanged();
    partial void OnexternvakNaamChanging(string value);
    partial void OnexternvakNaamChanged();
    partial void OnexternvakStudiepuntChanging(string value);
    partial void OnexternvakStudiepuntChanged();
    partial void OnexternvakJaarChanging(string value);
    partial void OnexternvakJaarChanged();
    partial void OnexternvakOpleidingChanging(string value);
    partial void OnexternvakOpleidingChanged();
    partial void OnexternvakSchoolChanging(string value);
    partial void OnexternvakSchoolChanged();
    #endregion
	
	public tblExternVak()
	{
		this._tblBijlages = new EntitySet<tblBijlage>(new Action<tblBijlage>(this.attach_tblBijlages), new Action<tblBijlage>(this.detach_tblBijlages));
		this._tblEvks = new EntitySet<tblEvk>(new Action<tblEvk>(this.attach_tblEvks), new Action<tblEvk>(this.detach_tblEvks));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_externvakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_externvakID
	{
		get
		{
			return this._pk_externvakID;
		}
		set
		{
			if ((this._pk_externvakID != value))
			{
				this.Onpk_externvakIDChanging(value);
				this.SendPropertyChanging();
				this._pk_externvakID = value;
				this.SendPropertyChanged("pk_externvakID");
				this.Onpk_externvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakNaam
	{
		get
		{
			return this._externvakNaam;
		}
		set
		{
			if ((this._externvakNaam != value))
			{
				this.OnexternvakNaamChanging(value);
				this.SendPropertyChanging();
				this._externvakNaam = value;
				this.SendPropertyChanged("externvakNaam");
				this.OnexternvakNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakStudiepunt", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakStudiepunt
	{
		get
		{
			return this._externvakStudiepunt;
		}
		set
		{
			if ((this._externvakStudiepunt != value))
			{
				this.OnexternvakStudiepuntChanging(value);
				this.SendPropertyChanging();
				this._externvakStudiepunt = value;
				this.SendPropertyChanged("externvakStudiepunt");
				this.OnexternvakStudiepuntChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakJaar", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakJaar
	{
		get
		{
			return this._externvakJaar;
		}
		set
		{
			if ((this._externvakJaar != value))
			{
				this.OnexternvakJaarChanging(value);
				this.SendPropertyChanging();
				this._externvakJaar = value;
				this.SendPropertyChanged("externvakJaar");
				this.OnexternvakJaarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakOpleiding", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakOpleiding
	{
		get
		{
			return this._externvakOpleiding;
		}
		set
		{
			if ((this._externvakOpleiding != value))
			{
				this.OnexternvakOpleidingChanging(value);
				this.SendPropertyChanging();
				this._externvakOpleiding = value;
				this.SendPropertyChanged("externvakOpleiding");
				this.OnexternvakOpleidingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakSchool", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakSchool
	{
		get
		{
			return this._externvakSchool;
		}
		set
		{
			if ((this._externvakSchool != value))
			{
				this.OnexternvakSchoolChanging(value);
				this.SendPropertyChanging();
				this._externvakSchool = value;
				this.SendPropertyChanged("externvakSchool");
				this.OnexternvakSchoolChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblExternVak_tblBijlage", Storage="_tblBijlages", ThisKey="pk_externvakID", OtherKey="fk_externvakID")]
	public EntitySet<tblBijlage> tblBijlages
	{
		get
		{
			return this._tblBijlages;
		}
		set
		{
			this._tblBijlages.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblExternVak_tblEvk", Storage="_tblEvks", ThisKey="pk_externvakID", OtherKey="fk_externvakID")]
	public EntitySet<tblEvk> tblEvks
	{
		get
		{
			return this._tblEvks;
		}
		set
		{
			this._tblEvks.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblBijlages(tblBijlage entity)
	{
		this.SendPropertyChanging();
		entity.tblExternVak = this;
	}
	
	private void detach_tblBijlages(tblBijlage entity)
	{
		this.SendPropertyChanging();
		entity.tblExternVak = null;
	}
	
	private void attach_tblEvks(tblEvk entity)
	{
		this.SendPropertyChanging();
		entity.tblExternVak = this;
	}
	
	private void detach_tblEvks(tblEvk entity)
	{
		this.SendPropertyChanging();
		entity.tblExternVak = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOpleiding")]
public partial class tblOpleiding : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_opleidingID;
	
	private string _opleidingNaam;
	
	private EntitySet<tblOpleidingVak> _tblOpleidingVaks;
	
	private EntitySet<tblStudent> _tblStudents;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_opleidingIDChanging(int value);
    partial void Onpk_opleidingIDChanged();
    partial void OnopleidingNaamChanging(string value);
    partial void OnopleidingNaamChanged();
    #endregion
	
	public tblOpleiding()
	{
		this._tblOpleidingVaks = new EntitySet<tblOpleidingVak>(new Action<tblOpleidingVak>(this.attach_tblOpleidingVaks), new Action<tblOpleidingVak>(this.detach_tblOpleidingVaks));
		this._tblStudents = new EntitySet<tblStudent>(new Action<tblStudent>(this.attach_tblStudents), new Action<tblStudent>(this.detach_tblStudents));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_opleidingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_opleidingID
	{
		get
		{
			return this._pk_opleidingID;
		}
		set
		{
			if ((this._pk_opleidingID != value))
			{
				this.Onpk_opleidingIDChanging(value);
				this.SendPropertyChanging();
				this._pk_opleidingID = value;
				this.SendPropertyChanged("pk_opleidingID");
				this.Onpk_opleidingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opleidingNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string opleidingNaam
	{
		get
		{
			return this._opleidingNaam;
		}
		set
		{
			if ((this._opleidingNaam != value))
			{
				this.OnopleidingNaamChanging(value);
				this.SendPropertyChanging();
				this._opleidingNaam = value;
				this.SendPropertyChanged("opleidingNaam");
				this.OnopleidingNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblOpleidingVak", Storage="_tblOpleidingVaks", ThisKey="pk_opleidingID", OtherKey="fk_opleidingID")]
	public EntitySet<tblOpleidingVak> tblOpleidingVaks
	{
		get
		{
			return this._tblOpleidingVaks;
		}
		set
		{
			this._tblOpleidingVaks.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblStudent", Storage="_tblStudents", ThisKey="pk_opleidingID", OtherKey="fk_opleidingID")]
	public EntitySet<tblStudent> tblStudents
	{
		get
		{
			return this._tblStudents;
		}
		set
		{
			this._tblStudents.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblOpleidingVaks(tblOpleidingVak entity)
	{
		this.SendPropertyChanging();
		entity.tblOpleiding = this;
	}
	
	private void detach_tblOpleidingVaks(tblOpleidingVak entity)
	{
		this.SendPropertyChanging();
		entity.tblOpleiding = null;
	}
	
	private void attach_tblStudents(tblStudent entity)
	{
		this.SendPropertyChanging();
		entity.tblOpleiding = this;
	}
	
	private void detach_tblStudents(tblStudent entity)
	{
		this.SendPropertyChanging();
		entity.tblOpleiding = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOpleidingVak")]
public partial class tblOpleidingVak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_opleidingvakID;
	
	private int _fk_opleidingID;
	
	private int _fk_vakID;
	
	private EntityRef<tblOpleiding> _tblOpleiding;
	
	private EntityRef<tblVak> _tblVak;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_opleidingvakIDChanging(int value);
    partial void Onpk_opleidingvakIDChanged();
    partial void Onfk_opleidingIDChanging(int value);
    partial void Onfk_opleidingIDChanged();
    partial void Onfk_vakIDChanging(int value);
    partial void Onfk_vakIDChanged();
    #endregion
	
	public tblOpleidingVak()
	{
		this._tblOpleiding = default(EntityRef<tblOpleiding>);
		this._tblVak = default(EntityRef<tblVak>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_opleidingvakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_opleidingvakID
	{
		get
		{
			return this._pk_opleidingvakID;
		}
		set
		{
			if ((this._pk_opleidingvakID != value))
			{
				this.Onpk_opleidingvakIDChanging(value);
				this.SendPropertyChanging();
				this._pk_opleidingvakID = value;
				this.SendPropertyChanged("pk_opleidingvakID");
				this.Onpk_opleidingvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_opleidingID", DbType="Int NOT NULL")]
	public int fk_opleidingID
	{
		get
		{
			return this._fk_opleidingID;
		}
		set
		{
			if ((this._fk_opleidingID != value))
			{
				if (this._tblOpleiding.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_opleidingIDChanging(value);
				this.SendPropertyChanging();
				this._fk_opleidingID = value;
				this.SendPropertyChanged("fk_opleidingID");
				this.Onfk_opleidingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vakID", DbType="Int NOT NULL")]
	public int fk_vakID
	{
		get
		{
			return this._fk_vakID;
		}
		set
		{
			if ((this._fk_vakID != value))
			{
				if (this._tblVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vakID = value;
				this.SendPropertyChanged("fk_vakID");
				this.Onfk_vakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblOpleidingVak", Storage="_tblOpleiding", ThisKey="fk_opleidingID", OtherKey="pk_opleidingID", IsForeignKey=true)]
	public tblOpleiding tblOpleiding
	{
		get
		{
			return this._tblOpleiding.Entity;
		}
		set
		{
			tblOpleiding previousValue = this._tblOpleiding.Entity;
			if (((previousValue != value) 
						|| (this._tblOpleiding.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblOpleiding.Entity = null;
					previousValue.tblOpleidingVaks.Remove(this);
				}
				this._tblOpleiding.Entity = value;
				if ((value != null))
				{
					value.tblOpleidingVaks.Add(this);
					this._fk_opleidingID = value.pk_opleidingID;
				}
				else
				{
					this._fk_opleidingID = default(int);
				}
				this.SendPropertyChanged("tblOpleiding");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblOpleidingVak", Storage="_tblVak", ThisKey="fk_vakID", OtherKey="pk_vakID", IsForeignKey=true)]
	public tblVak tblVak
	{
		get
		{
			return this._tblVak.Entity;
		}
		set
		{
			tblVak previousValue = this._tblVak.Entity;
			if (((previousValue != value) 
						|| (this._tblVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVak.Entity = null;
					previousValue.tblOpleidingVaks.Remove(this);
				}
				this._tblVak.Entity = value;
				if ((value != null))
				{
					value.tblOpleidingVaks.Add(this);
					this._fk_vakID = value.pk_vakID;
				}
				else
				{
					this._fk_vakID = default(int);
				}
				this.SendPropertyChanged("tblVak");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudent")]
public partial class tblStudent : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_studentID;
	
	private string _studentNaam;
	
	private string _studentVoornaam;
	
	private string _studentPasswoord;
	
	private string _studentNummer;
	
	private int _fk_opleidingID;
	
	private EntitySet<tblEvk> _tblEvks;
	
	private EntityRef<tblOpleiding> _tblOpleiding;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_studentIDChanging(int value);
    partial void Onpk_studentIDChanged();
    partial void OnstudentNaamChanging(string value);
    partial void OnstudentNaamChanged();
    partial void OnstudentVoornaamChanging(string value);
    partial void OnstudentVoornaamChanged();
    partial void OnstudentPasswoordChanging(string value);
    partial void OnstudentPasswoordChanged();
    partial void OnstudentNummerChanging(string value);
    partial void OnstudentNummerChanged();
    partial void Onfk_opleidingIDChanging(int value);
    partial void Onfk_opleidingIDChanged();
    #endregion
	
	public tblStudent()
	{
		this._tblEvks = new EntitySet<tblEvk>(new Action<tblEvk>(this.attach_tblEvks), new Action<tblEvk>(this.detach_tblEvks));
		this._tblOpleiding = default(EntityRef<tblOpleiding>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_studentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_studentID
	{
		get
		{
			return this._pk_studentID;
		}
		set
		{
			if ((this._pk_studentID != value))
			{
				this.Onpk_studentIDChanging(value);
				this.SendPropertyChanging();
				this._pk_studentID = value;
				this.SendPropertyChanged("pk_studentID");
				this.Onpk_studentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentNaam
	{
		get
		{
			return this._studentNaam;
		}
		set
		{
			if ((this._studentNaam != value))
			{
				this.OnstudentNaamChanging(value);
				this.SendPropertyChanging();
				this._studentNaam = value;
				this.SendPropertyChanged("studentNaam");
				this.OnstudentNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentVoornaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentVoornaam
	{
		get
		{
			return this._studentVoornaam;
		}
		set
		{
			if ((this._studentVoornaam != value))
			{
				this.OnstudentVoornaamChanging(value);
				this.SendPropertyChanging();
				this._studentVoornaam = value;
				this.SendPropertyChanged("studentVoornaam");
				this.OnstudentVoornaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentPasswoord", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentPasswoord
	{
		get
		{
			return this._studentPasswoord;
		}
		set
		{
			if ((this._studentPasswoord != value))
			{
				this.OnstudentPasswoordChanging(value);
				this.SendPropertyChanging();
				this._studentPasswoord = value;
				this.SendPropertyChanged("studentPasswoord");
				this.OnstudentPasswoordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNummer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentNummer
	{
		get
		{
			return this._studentNummer;
		}
		set
		{
			if ((this._studentNummer != value))
			{
				this.OnstudentNummerChanging(value);
				this.SendPropertyChanging();
				this._studentNummer = value;
				this.SendPropertyChanged("studentNummer");
				this.OnstudentNummerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_opleidingID", DbType="Int NOT NULL")]
	public int fk_opleidingID
	{
		get
		{
			return this._fk_opleidingID;
		}
		set
		{
			if ((this._fk_opleidingID != value))
			{
				if (this._tblOpleiding.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_opleidingIDChanging(value);
				this.SendPropertyChanging();
				this._fk_opleidingID = value;
				this.SendPropertyChanged("fk_opleidingID");
				this.Onfk_opleidingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblEvk", Storage="_tblEvks", ThisKey="pk_studentID", OtherKey="fk_studentID")]
	public EntitySet<tblEvk> tblEvks
	{
		get
		{
			return this._tblEvks;
		}
		set
		{
			this._tblEvks.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblStudent", Storage="_tblOpleiding", ThisKey="fk_opleidingID", OtherKey="pk_opleidingID", IsForeignKey=true)]
	public tblOpleiding tblOpleiding
	{
		get
		{
			return this._tblOpleiding.Entity;
		}
		set
		{
			tblOpleiding previousValue = this._tblOpleiding.Entity;
			if (((previousValue != value) 
						|| (this._tblOpleiding.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblOpleiding.Entity = null;
					previousValue.tblStudents.Remove(this);
				}
				this._tblOpleiding.Entity = value;
				if ((value != null))
				{
					value.tblStudents.Add(this);
					this._fk_opleidingID = value.pk_opleidingID;
				}
				else
				{
					this._fk_opleidingID = default(int);
				}
				this.SendPropertyChanged("tblOpleiding");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblEvks(tblEvk entity)
	{
		this.SendPropertyChanging();
		entity.tblStudent = this;
	}
	
	private void detach_tblEvks(tblEvk entity)
	{
		this.SendPropertyChanging();
		entity.tblStudent = null;
	}
}
#pragma warning restore 1591
