#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class dc_databankDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBijlage(Bijlage instance);
  partial void UpdateBijlage(Bijlage instance);
  partial void DeleteBijlage(Bijlage instance);
  partial void InsertVak(Vak instance);
  partial void UpdateVak(Vak instance);
  partial void DeleteVak(Vak instance);
  partial void InsertDocent(Docent instance);
  partial void UpdateDocent(Docent instance);
  partial void DeleteDocent(Docent instance);
  partial void InsertDocentVak(DocentVak instance);
  partial void UpdateDocentVak(DocentVak instance);
  partial void DeleteDocentVak(DocentVak instance);
  partial void InsertEvk(Evk instance);
  partial void UpdateEvk(Evk instance);
  partial void DeleteEvk(Evk instance);
  partial void InsertExternVak(ExternVak instance);
  partial void UpdateExternVak(ExternVak instance);
  partial void DeleteExternVak(ExternVak instance);
  partial void InsertOpleiding(Opleiding instance);
  partial void UpdateOpleiding(Opleiding instance);
  partial void DeleteOpleiding(Opleiding instance);
  partial void InsertOpleidingVak(OpleidingVak instance);
  partial void UpdateOpleidingVak(OpleidingVak instance);
  partial void DeleteOpleidingVak(OpleidingVak instance);
  partial void InsertStudent(Student instance);
  partial void UpdateStudent(Student instance);
  partial void DeleteStudent(Student instance);
  #endregion
	
	public dc_databankDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dc_databankDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dc_databankDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dc_databankDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dc_databankDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Bijlage> Bijlages
	{
		get
		{
			return this.GetTable<Bijlage>();
		}
	}
	
	public System.Data.Linq.Table<Vak> Vaks
	{
		get
		{
			return this.GetTable<Vak>();
		}
	}
	
	public System.Data.Linq.Table<Docent> Docents
	{
		get
		{
			return this.GetTable<Docent>();
		}
	}
	
	public System.Data.Linq.Table<DocentVak> DocentVaks
	{
		get
		{
			return this.GetTable<DocentVak>();
		}
	}
	
	public System.Data.Linq.Table<Evk> Evks
	{
		get
		{
			return this.GetTable<Evk>();
		}
	}
	
	public System.Data.Linq.Table<ExternVak> ExternVaks
	{
		get
		{
			return this.GetTable<ExternVak>();
		}
	}
	
	public System.Data.Linq.Table<Opleiding> Opleidings
	{
		get
		{
			return this.GetTable<Opleiding>();
		}
	}
	
	public System.Data.Linq.Table<OpleidingVak> OpleidingVaks
	{
		get
		{
			return this.GetTable<OpleidingVak>();
		}
	}
	
	public System.Data.Linq.Table<Student> Students
	{
		get
		{
			return this.GetTable<Student>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBijlage")]
public partial class Bijlage : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_bijlageID;
	
	private string _bijlageURL;
	
	private string _bijlageTitel;
	
	private string _bijlageType;
	
	private int _fk_externvakID;
	
	private EntityRef<ExternVak> _tblExternVak;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_bijlageIDChanging(int value);
    partial void Onpk_bijlageIDChanged();
    partial void OnbijlageURLChanging(string value);
    partial void OnbijlageURLChanged();
    partial void OnbijlageTitelChanging(string value);
    partial void OnbijlageTitelChanged();
    partial void OnbijlageTypeChanging(string value);
    partial void OnbijlageTypeChanged();
    partial void Onfk_externvakIDChanging(int value);
    partial void Onfk_externvakIDChanged();
    #endregion
	
	public Bijlage()
	{
		this._tblExternVak = default(EntityRef<ExternVak>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_bijlageID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_bijlageID
	{
		get
		{
			return this._pk_bijlageID;
		}
		set
		{
			if ((this._pk_bijlageID != value))
			{
				this.Onpk_bijlageIDChanging(value);
				this.SendPropertyChanging();
				this._pk_bijlageID = value;
				this.SendPropertyChanged("pk_bijlageID");
				this.Onpk_bijlageIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bijlageURL", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string bijlageURL
	{
		get
		{
			return this._bijlageURL;
		}
		set
		{
			if ((this._bijlageURL != value))
			{
				this.OnbijlageURLChanging(value);
				this.SendPropertyChanging();
				this._bijlageURL = value;
				this.SendPropertyChanged("bijlageURL");
				this.OnbijlageURLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bijlageTitel", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string bijlageTitel
	{
		get
		{
			return this._bijlageTitel;
		}
		set
		{
			if ((this._bijlageTitel != value))
			{
				this.OnbijlageTitelChanging(value);
				this.SendPropertyChanging();
				this._bijlageTitel = value;
				this.SendPropertyChanged("bijlageTitel");
				this.OnbijlageTitelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bijlageType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string bijlageType
	{
		get
		{
			return this._bijlageType;
		}
		set
		{
			if ((this._bijlageType != value))
			{
				this.OnbijlageTypeChanging(value);
				this.SendPropertyChanging();
				this._bijlageType = value;
				this.SendPropertyChanged("bijlageType");
				this.OnbijlageTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_externvakID", DbType="Int NOT NULL")]
	public int fk_externvakID
	{
		get
		{
			return this._fk_externvakID;
		}
		set
		{
			if ((this._fk_externvakID != value))
			{
				if (this._tblExternVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_externvakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_externvakID = value;
				this.SendPropertyChanged("fk_externvakID");
				this.Onfk_externvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblExternVak_tblBijlage", Storage="_tblExternVak", ThisKey="fk_externvakID", OtherKey="pk_externvakID", IsForeignKey=true)]
	public ExternVak ExternVak
	{
		get
		{
			return this._tblExternVak.Entity;
		}
		set
		{
			ExternVak previousValue = this._tblExternVak.Entity;
			if (((previousValue != value) 
						|| (this._tblExternVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblExternVak.Entity = null;
					previousValue.Bijlages.Remove(this);
				}
				this._tblExternVak.Entity = value;
				if ((value != null))
				{
					value.Bijlages.Add(this);
					this._fk_externvakID = value.pk_externvakID;
				}
				else
				{
					this._fk_externvakID = default(int);
				}
				this.SendPropertyChanged("ExternVak");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVak")]
public partial class Vak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_vakID;
	
	private string _vakNaam;
	
	private int _vakStudiepunten;
	
	private EntitySet<DocentVak> _tblDocentVaks;
	
	private EntitySet<Evk> _tblEvks;
	
	private EntitySet<OpleidingVak> _tblOpleidingVaks;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_vakIDChanging(int value);
    partial void Onpk_vakIDChanged();
    partial void OnvakNaamChanging(string value);
    partial void OnvakNaamChanged();
    partial void OnvakStudiepuntenChanging(int value);
    partial void OnvakStudiepuntenChanged();
    #endregion
	
	public Vak()
	{
		this._tblDocentVaks = new EntitySet<DocentVak>(new Action<DocentVak>(this.attach_tblDocentVaks), new Action<DocentVak>(this.detach_tblDocentVaks));
		this._tblEvks = new EntitySet<Evk>(new Action<Evk>(this.attach_tblEvks), new Action<Evk>(this.detach_tblEvks));
		this._tblOpleidingVaks = new EntitySet<OpleidingVak>(new Action<OpleidingVak>(this.attach_tblOpleidingVaks), new Action<OpleidingVak>(this.detach_tblOpleidingVaks));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_vakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_vakID
	{
		get
		{
			return this._pk_vakID;
		}
		set
		{
			if ((this._pk_vakID != value))
			{
				this.Onpk_vakIDChanging(value);
				this.SendPropertyChanging();
				this._pk_vakID = value;
				this.SendPropertyChanged("pk_vakID");
				this.Onpk_vakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vakNaam", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vakNaam
	{
		get
		{
			return this._vakNaam;
		}
		set
		{
			if ((this._vakNaam != value))
			{
				this.OnvakNaamChanging(value);
				this.SendPropertyChanging();
				this._vakNaam = value;
				this.SendPropertyChanged("vakNaam");
				this.OnvakNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vakStudiepunten", DbType="Int NOT NULL")]
	public int vakStudiepunten
	{
		get
		{
			return this._vakStudiepunten;
		}
		set
		{
			if ((this._vakStudiepunten != value))
			{
				this.OnvakStudiepuntenChanging(value);
				this.SendPropertyChanging();
				this._vakStudiepunten = value;
				this.SendPropertyChanged("vakStudiepunten");
				this.OnvakStudiepuntenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblDocentVak", Storage="_tblDocentVaks", ThisKey="pk_vakID", OtherKey="fk_vakID")]
	public EntitySet<DocentVak> DocentVaks
	{
		get
		{
			return this._tblDocentVaks;
		}
		set
		{
			this._tblDocentVaks.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblEvk", Storage="_tblEvks", ThisKey="pk_vakID", OtherKey="fk_vakID")]
	public EntitySet<Evk> Evks
	{
		get
		{
			return this._tblEvks;
		}
		set
		{
			this._tblEvks.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblOpleidingVak", Storage="_tblOpleidingVaks", ThisKey="pk_vakID", OtherKey="fk_vakID")]
	public EntitySet<OpleidingVak> OpleidingVaks
	{
		get
		{
			return this._tblOpleidingVaks;
		}
		set
		{
			this._tblOpleidingVaks.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblDocentVaks(DocentVak entity)
	{
		this.SendPropertyChanging();
		entity.Vak = this;
	}
	
	private void detach_tblDocentVaks(DocentVak entity)
	{
		this.SendPropertyChanging();
		entity.Vak = null;
	}
	
	private void attach_tblEvks(Evk entity)
	{
		this.SendPropertyChanging();
		entity.Vak = this;
	}
	
	private void detach_tblEvks(Evk entity)
	{
		this.SendPropertyChanging();
		entity.Vak = null;
	}
	
	private void attach_tblOpleidingVaks(OpleidingVak entity)
	{
		this.SendPropertyChanging();
		entity.Vak = this;
	}
	
	private void detach_tblOpleidingVaks(OpleidingVak entity)
	{
		this.SendPropertyChanging();
		entity.Vak = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDocent")]
public partial class Docent : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_docentID;
	
	private string _docentNaam;
	
	private string _docentWachtwoord;
	
	private double _docentAdmin;
	
	private EntitySet<DocentVak> _tblDocentVaks;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_docentIDChanging(int value);
    partial void Onpk_docentIDChanged();
    partial void OndocentNaamChanging(string value);
    partial void OndocentNaamChanged();
    partial void OndocentWachtwoordChanging(string value);
    partial void OndocentWachtwoordChanged();
    partial void OndocentAdminChanging(double value);
    partial void OndocentAdminChanged();
    #endregion
	
	public Docent()
	{
		this._tblDocentVaks = new EntitySet<DocentVak>(new Action<DocentVak>(this.attach_tblDocentVaks), new Action<DocentVak>(this.detach_tblDocentVaks));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_docentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_docentID
	{
		get
		{
			return this._pk_docentID;
		}
		set
		{
			if ((this._pk_docentID != value))
			{
				this.Onpk_docentIDChanging(value);
				this.SendPropertyChanging();
				this._pk_docentID = value;
				this.SendPropertyChanged("pk_docentID");
				this.Onpk_docentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docentNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string docentNaam
	{
		get
		{
			return this._docentNaam;
		}
		set
		{
			if ((this._docentNaam != value))
			{
				this.OndocentNaamChanging(value);
				this.SendPropertyChanging();
				this._docentNaam = value;
				this.SendPropertyChanged("docentNaam");
				this.OndocentNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docentWachtwoord", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string docentWachtwoord
	{
		get
		{
			return this._docentWachtwoord;
		}
		set
		{
			if ((this._docentWachtwoord != value))
			{
				this.OndocentWachtwoordChanging(value);
				this.SendPropertyChanging();
				this._docentWachtwoord = value;
				this.SendPropertyChanged("docentWachtwoord");
				this.OndocentWachtwoordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docentAdmin", DbType="Float NOT NULL")]
	public double docentAdmin
	{
		get
		{
			return this._docentAdmin;
		}
		set
		{
			if ((this._docentAdmin != value))
			{
				this.OndocentAdminChanging(value);
				this.SendPropertyChanging();
				this._docentAdmin = value;
				this.SendPropertyChanged("docentAdmin");
				this.OndocentAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDocent_tblDocentVak", Storage="_tblDocentVaks", ThisKey="pk_docentID", OtherKey="fk_docentID")]
	public EntitySet<DocentVak> DocentVaks
	{
		get
		{
			return this._tblDocentVaks;
		}
		set
		{
			this._tblDocentVaks.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblDocentVaks(DocentVak entity)
	{
		this.SendPropertyChanging();
		entity.Docent = this;
	}
	
	private void detach_tblDocentVaks(DocentVak entity)
	{
		this.SendPropertyChanging();
		entity.Docent = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDocentVak")]
public partial class DocentVak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_docentvakID;
	
	private int _fk_vakID;
	
	private int _fk_docentID;
	
	private EntityRef<Docent> _tblDocent;
	
	private EntityRef<Vak> _tblVak;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_docentvakIDChanging(int value);
    partial void Onpk_docentvakIDChanged();
    partial void Onfk_vakIDChanging(int value);
    partial void Onfk_vakIDChanged();
    partial void Onfk_docentIDChanging(int value);
    partial void Onfk_docentIDChanged();
    #endregion
	
	public DocentVak()
	{
		this._tblDocent = default(EntityRef<Docent>);
		this._tblVak = default(EntityRef<Vak>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_docentvakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_docentvakID
	{
		get
		{
			return this._pk_docentvakID;
		}
		set
		{
			if ((this._pk_docentvakID != value))
			{
				this.Onpk_docentvakIDChanging(value);
				this.SendPropertyChanging();
				this._pk_docentvakID = value;
				this.SendPropertyChanged("pk_docentvakID");
				this.Onpk_docentvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vakID", DbType="Int NOT NULL")]
	public int fk_vakID
	{
		get
		{
			return this._fk_vakID;
		}
		set
		{
			if ((this._fk_vakID != value))
			{
				if (this._tblVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vakID = value;
				this.SendPropertyChanged("fk_vakID");
				this.Onfk_vakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_docentID", DbType="Int NOT NULL")]
	public int fk_docentID
	{
		get
		{
			return this._fk_docentID;
		}
		set
		{
			if ((this._fk_docentID != value))
			{
				if (this._tblDocent.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_docentIDChanging(value);
				this.SendPropertyChanging();
				this._fk_docentID = value;
				this.SendPropertyChanged("fk_docentID");
				this.Onfk_docentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDocent_tblDocentVak", Storage="_tblDocent", ThisKey="fk_docentID", OtherKey="pk_docentID", IsForeignKey=true)]
	public Docent Docent
	{
		get
		{
			return this._tblDocent.Entity;
		}
		set
		{
			Docent previousValue = this._tblDocent.Entity;
			if (((previousValue != value) 
						|| (this._tblDocent.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblDocent.Entity = null;
					previousValue.DocentVaks.Remove(this);
				}
				this._tblDocent.Entity = value;
				if ((value != null))
				{
					value.DocentVaks.Add(this);
					this._fk_docentID = value.pk_docentID;
				}
				else
				{
					this._fk_docentID = default(int);
				}
				this.SendPropertyChanged("Docent");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblDocentVak", Storage="_tblVak", ThisKey="fk_vakID", OtherKey="pk_vakID", IsForeignKey=true)]
	public Vak Vak
	{
		get
		{
			return this._tblVak.Entity;
		}
		set
		{
			Vak previousValue = this._tblVak.Entity;
			if (((previousValue != value) 
						|| (this._tblVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVak.Entity = null;
					previousValue.DocentVaks.Remove(this);
				}
				this._tblVak.Entity = value;
				if ((value != null))
				{
					value.DocentVaks.Add(this);
					this._fk_vakID = value.pk_vakID;
				}
				else
				{
					this._fk_vakID = default(int);
				}
				this.SendPropertyChanged("Vak");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEvk")]
public partial class Evk : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_evkID;
	
	private int _fk_studentID;
	
	private int _fk_vakID;
	
	private int _fk_externvakID;
	
	private double _evkDocentGoedgekeurd;
	
	private double _evkAdminGoedgekeurd;
	
	private EntityRef<Vak> _tblVak;
	
	private EntityRef<ExternVak> _tblExternVak;
	
	private EntityRef<Student> _tblStudent;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_evkIDChanging(int value);
    partial void Onpk_evkIDChanged();
    partial void Onfk_studentIDChanging(int value);
    partial void Onfk_studentIDChanged();
    partial void Onfk_vakIDChanging(int value);
    partial void Onfk_vakIDChanged();
    partial void Onfk_externvakIDChanging(int value);
    partial void Onfk_externvakIDChanged();
    partial void OnevkDocentGoedgekeurdChanging(double value);
    partial void OnevkDocentGoedgekeurdChanged();
    partial void OnevkAdminGoedgekeurdChanging(double value);
    partial void OnevkAdminGoedgekeurdChanged();
    #endregion
	
	public Evk()
	{
		this._tblVak = default(EntityRef<Vak>);
		this._tblExternVak = default(EntityRef<ExternVak>);
		this._tblStudent = default(EntityRef<Student>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_evkID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_evkID
	{
		get
		{
			return this._pk_evkID;
		}
		set
		{
			if ((this._pk_evkID != value))
			{
				this.Onpk_evkIDChanging(value);
				this.SendPropertyChanging();
				this._pk_evkID = value;
				this.SendPropertyChanged("pk_evkID");
				this.Onpk_evkIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_studentID", DbType="Int NOT NULL")]
	public int fk_studentID
	{
		get
		{
			return this._fk_studentID;
		}
		set
		{
			if ((this._fk_studentID != value))
			{
				if (this._tblStudent.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_studentIDChanging(value);
				this.SendPropertyChanging();
				this._fk_studentID = value;
				this.SendPropertyChanged("fk_studentID");
				this.Onfk_studentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vakID", DbType="Int NOT NULL")]
	public int fk_vakID
	{
		get
		{
			return this._fk_vakID;
		}
		set
		{
			if ((this._fk_vakID != value))
			{
				if (this._tblVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vakID = value;
				this.SendPropertyChanged("fk_vakID");
				this.Onfk_vakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_externvakID", DbType="Int NOT NULL")]
	public int fk_externvakID
	{
		get
		{
			return this._fk_externvakID;
		}
		set
		{
			if ((this._fk_externvakID != value))
			{
				if (this._tblExternVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_externvakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_externvakID = value;
				this.SendPropertyChanged("fk_externvakID");
				this.Onfk_externvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evkDocentGoedgekeurd", DbType="Float NOT NULL")]
	public double evkDocentGoedgekeurd
	{
		get
		{
			return this._evkDocentGoedgekeurd;
		}
		set
		{
			if ((this._evkDocentGoedgekeurd != value))
			{
				this.OnevkDocentGoedgekeurdChanging(value);
				this.SendPropertyChanging();
				this._evkDocentGoedgekeurd = value;
				this.SendPropertyChanged("evkDocentGoedgekeurd");
				this.OnevkDocentGoedgekeurdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evkAdminGoedgekeurd", DbType="Float NOT NULL")]
	public double evkAdminGoedgekeurd
	{
		get
		{
			return this._evkAdminGoedgekeurd;
		}
		set
		{
			if ((this._evkAdminGoedgekeurd != value))
			{
				this.OnevkAdminGoedgekeurdChanging(value);
				this.SendPropertyChanging();
				this._evkAdminGoedgekeurd = value;
				this.SendPropertyChanged("evkAdminGoedgekeurd");
				this.OnevkAdminGoedgekeurdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblEvk", Storage="_tblVak", ThisKey="fk_vakID", OtherKey="pk_vakID", IsForeignKey=true)]
	public Vak Vak
	{
		get
		{
			return this._tblVak.Entity;
		}
		set
		{
			Vak previousValue = this._tblVak.Entity;
			if (((previousValue != value) 
						|| (this._tblVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVak.Entity = null;
					previousValue.Evks.Remove(this);
				}
				this._tblVak.Entity = value;
				if ((value != null))
				{
					value.Evks.Add(this);
					this._fk_vakID = value.pk_vakID;
				}
				else
				{
					this._fk_vakID = default(int);
				}
				this.SendPropertyChanged("Vak");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblExternVak_tblEvk", Storage="_tblExternVak", ThisKey="fk_externvakID", OtherKey="pk_externvakID", IsForeignKey=true)]
	public ExternVak ExternVak
	{
		get
		{
			return this._tblExternVak.Entity;
		}
		set
		{
			ExternVak previousValue = this._tblExternVak.Entity;
			if (((previousValue != value) 
						|| (this._tblExternVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblExternVak.Entity = null;
					previousValue.Evks.Remove(this);
				}
				this._tblExternVak.Entity = value;
				if ((value != null))
				{
					value.Evks.Add(this);
					this._fk_externvakID = value.pk_externvakID;
				}
				else
				{
					this._fk_externvakID = default(int);
				}
				this.SendPropertyChanged("ExternVak");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblEvk", Storage="_tblStudent", ThisKey="fk_studentID", OtherKey="pk_studentID", IsForeignKey=true)]
	public Student Student
	{
		get
		{
			return this._tblStudent.Entity;
		}
		set
		{
			Student previousValue = this._tblStudent.Entity;
			if (((previousValue != value) 
						|| (this._tblStudent.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblStudent.Entity = null;
					previousValue.Evks.Remove(this);
				}
				this._tblStudent.Entity = value;
				if ((value != null))
				{
					value.Evks.Add(this);
					this._fk_studentID = value.pk_studentID;
				}
				else
				{
					this._fk_studentID = default(int);
				}
				this.SendPropertyChanged("Student");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblExternVak")]
public partial class ExternVak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_externvakID;
	
	private string _externvakNaam;
	
	private string _externvakStudiepunt;
	
	private string _externvakJaar;
	
	private string _externvakOpleiding;
	
	private string _externvakSchool;
	
	private EntitySet<Bijlage> _tblBijlages;
	
	private EntitySet<Evk> _tblEvks;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_externvakIDChanging(int value);
    partial void Onpk_externvakIDChanged();
    partial void OnexternvakNaamChanging(string value);
    partial void OnexternvakNaamChanged();
    partial void OnexternvakStudiepuntChanging(string value);
    partial void OnexternvakStudiepuntChanged();
    partial void OnexternvakJaarChanging(string value);
    partial void OnexternvakJaarChanged();
    partial void OnexternvakOpleidingChanging(string value);
    partial void OnexternvakOpleidingChanged();
    partial void OnexternvakSchoolChanging(string value);
    partial void OnexternvakSchoolChanged();
    #endregion
	
	public ExternVak()
	{
		this._tblBijlages = new EntitySet<Bijlage>(new Action<Bijlage>(this.attach_tblBijlages), new Action<Bijlage>(this.detach_tblBijlages));
		this._tblEvks = new EntitySet<Evk>(new Action<Evk>(this.attach_tblEvks), new Action<Evk>(this.detach_tblEvks));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_externvakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_externvakID
	{
		get
		{
			return this._pk_externvakID;
		}
		set
		{
			if ((this._pk_externvakID != value))
			{
				this.Onpk_externvakIDChanging(value);
				this.SendPropertyChanging();
				this._pk_externvakID = value;
				this.SendPropertyChanged("pk_externvakID");
				this.Onpk_externvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakNaam
	{
		get
		{
			return this._externvakNaam;
		}
		set
		{
			if ((this._externvakNaam != value))
			{
				this.OnexternvakNaamChanging(value);
				this.SendPropertyChanging();
				this._externvakNaam = value;
				this.SendPropertyChanged("externvakNaam");
				this.OnexternvakNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakStudiepunt", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakStudiepunt
	{
		get
		{
			return this._externvakStudiepunt;
		}
		set
		{
			if ((this._externvakStudiepunt != value))
			{
				this.OnexternvakStudiepuntChanging(value);
				this.SendPropertyChanging();
				this._externvakStudiepunt = value;
				this.SendPropertyChanged("externvakStudiepunt");
				this.OnexternvakStudiepuntChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakJaar", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakJaar
	{
		get
		{
			return this._externvakJaar;
		}
		set
		{
			if ((this._externvakJaar != value))
			{
				this.OnexternvakJaarChanging(value);
				this.SendPropertyChanging();
				this._externvakJaar = value;
				this.SendPropertyChanged("externvakJaar");
				this.OnexternvakJaarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakOpleiding", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakOpleiding
	{
		get
		{
			return this._externvakOpleiding;
		}
		set
		{
			if ((this._externvakOpleiding != value))
			{
				this.OnexternvakOpleidingChanging(value);
				this.SendPropertyChanging();
				this._externvakOpleiding = value;
				this.SendPropertyChanged("externvakOpleiding");
				this.OnexternvakOpleidingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externvakSchool", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string externvakSchool
	{
		get
		{
			return this._externvakSchool;
		}
		set
		{
			if ((this._externvakSchool != value))
			{
				this.OnexternvakSchoolChanging(value);
				this.SendPropertyChanging();
				this._externvakSchool = value;
				this.SendPropertyChanged("externvakSchool");
				this.OnexternvakSchoolChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblExternVak_tblBijlage", Storage="_tblBijlages", ThisKey="pk_externvakID", OtherKey="fk_externvakID")]
	public EntitySet<Bijlage> Bijlages
	{
		get
		{
			return this._tblBijlages;
		}
		set
		{
			this._tblBijlages.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblExternVak_tblEvk", Storage="_tblEvks", ThisKey="pk_externvakID", OtherKey="fk_externvakID")]
	public EntitySet<Evk> Evks
	{
		get
		{
			return this._tblEvks;
		}
		set
		{
			this._tblEvks.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblBijlages(Bijlage entity)
	{
		this.SendPropertyChanging();
		entity.ExternVak = this;
	}
	
	private void detach_tblBijlages(Bijlage entity)
	{
		this.SendPropertyChanging();
		entity.ExternVak = null;
	}
	
	private void attach_tblEvks(Evk entity)
	{
		this.SendPropertyChanging();
		entity.ExternVak = this;
	}
	
	private void detach_tblEvks(Evk entity)
	{
		this.SendPropertyChanging();
		entity.ExternVak = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOpleiding")]
public partial class Opleiding : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_opleidingID;
	
	private string _opleidingNaam;
	
	private EntitySet<OpleidingVak> _tblOpleidingVaks;
	
	private EntitySet<Student> _tblStudents;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_opleidingIDChanging(int value);
    partial void Onpk_opleidingIDChanged();
    partial void OnopleidingNaamChanging(string value);
    partial void OnopleidingNaamChanged();
    #endregion
	
	public Opleiding()
	{
		this._tblOpleidingVaks = new EntitySet<OpleidingVak>(new Action<OpleidingVak>(this.attach_tblOpleidingVaks), new Action<OpleidingVak>(this.detach_tblOpleidingVaks));
		this._tblStudents = new EntitySet<Student>(new Action<Student>(this.attach_tblStudents), new Action<Student>(this.detach_tblStudents));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_opleidingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_opleidingID
	{
		get
		{
			return this._pk_opleidingID;
		}
		set
		{
			if ((this._pk_opleidingID != value))
			{
				this.Onpk_opleidingIDChanging(value);
				this.SendPropertyChanging();
				this._pk_opleidingID = value;
				this.SendPropertyChanged("pk_opleidingID");
				this.Onpk_opleidingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opleidingNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string opleidingNaam
	{
		get
		{
			return this._opleidingNaam;
		}
		set
		{
			if ((this._opleidingNaam != value))
			{
				this.OnopleidingNaamChanging(value);
				this.SendPropertyChanging();
				this._opleidingNaam = value;
				this.SendPropertyChanged("opleidingNaam");
				this.OnopleidingNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblOpleidingVak", Storage="_tblOpleidingVaks", ThisKey="pk_opleidingID", OtherKey="fk_opleidingID")]
	public EntitySet<OpleidingVak> OpleidingVaks
	{
		get
		{
			return this._tblOpleidingVaks;
		}
		set
		{
			this._tblOpleidingVaks.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblStudent", Storage="_tblStudents", ThisKey="pk_opleidingID", OtherKey="fk_opleidingID")]
	public EntitySet<Student> Students
	{
		get
		{
			return this._tblStudents;
		}
		set
		{
			this._tblStudents.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblOpleidingVaks(OpleidingVak entity)
	{
		this.SendPropertyChanging();
		entity.Opleiding = this;
	}
	
	private void detach_tblOpleidingVaks(OpleidingVak entity)
	{
		this.SendPropertyChanging();
		entity.Opleiding = null;
	}
	
	private void attach_tblStudents(Student entity)
	{
		this.SendPropertyChanging();
		entity.Opleiding = this;
	}
	
	private void detach_tblStudents(Student entity)
	{
		this.SendPropertyChanging();
		entity.Opleiding = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOpleidingVak")]
public partial class OpleidingVak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_opleidingvakID;
	
	private int _fk_opleidingID;
	
	private int _fk_vakID;
	
	private EntityRef<Opleiding> _tblOpleiding;
	
	private EntityRef<Vak> _tblVak;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_opleidingvakIDChanging(int value);
    partial void Onpk_opleidingvakIDChanged();
    partial void Onfk_opleidingIDChanging(int value);
    partial void Onfk_opleidingIDChanged();
    partial void Onfk_vakIDChanging(int value);
    partial void Onfk_vakIDChanged();
    #endregion
	
	public OpleidingVak()
	{
		this._tblOpleiding = default(EntityRef<Opleiding>);
		this._tblVak = default(EntityRef<Vak>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_opleidingvakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_opleidingvakID
	{
		get
		{
			return this._pk_opleidingvakID;
		}
		set
		{
			if ((this._pk_opleidingvakID != value))
			{
				this.Onpk_opleidingvakIDChanging(value);
				this.SendPropertyChanging();
				this._pk_opleidingvakID = value;
				this.SendPropertyChanged("pk_opleidingvakID");
				this.Onpk_opleidingvakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_opleidingID", DbType="Int NOT NULL")]
	public int fk_opleidingID
	{
		get
		{
			return this._fk_opleidingID;
		}
		set
		{
			if ((this._fk_opleidingID != value))
			{
				if (this._tblOpleiding.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_opleidingIDChanging(value);
				this.SendPropertyChanging();
				this._fk_opleidingID = value;
				this.SendPropertyChanged("fk_opleidingID");
				this.Onfk_opleidingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vakID", DbType="Int NOT NULL")]
	public int fk_vakID
	{
		get
		{
			return this._fk_vakID;
		}
		set
		{
			if ((this._fk_vakID != value))
			{
				if (this._tblVak.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vakIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vakID = value;
				this.SendPropertyChanged("fk_vakID");
				this.Onfk_vakIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblOpleidingVak", Storage="_tblOpleiding", ThisKey="fk_opleidingID", OtherKey="pk_opleidingID", IsForeignKey=true)]
	public Opleiding Opleiding
	{
		get
		{
			return this._tblOpleiding.Entity;
		}
		set
		{
			Opleiding previousValue = this._tblOpleiding.Entity;
			if (((previousValue != value) 
						|| (this._tblOpleiding.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblOpleiding.Entity = null;
					previousValue.OpleidingVaks.Remove(this);
				}
				this._tblOpleiding.Entity = value;
				if ((value != null))
				{
					value.OpleidingVaks.Add(this);
					this._fk_opleidingID = value.pk_opleidingID;
				}
				else
				{
					this._fk_opleidingID = default(int);
				}
				this.SendPropertyChanged("Opleiding");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVak_tblOpleidingVak", Storage="_tblVak", ThisKey="fk_vakID", OtherKey="pk_vakID", IsForeignKey=true)]
	public Vak Vak
	{
		get
		{
			return this._tblVak.Entity;
		}
		set
		{
			Vak previousValue = this._tblVak.Entity;
			if (((previousValue != value) 
						|| (this._tblVak.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVak.Entity = null;
					previousValue.OpleidingVaks.Remove(this);
				}
				this._tblVak.Entity = value;
				if ((value != null))
				{
					value.OpleidingVaks.Add(this);
					this._fk_vakID = value.pk_vakID;
				}
				else
				{
					this._fk_vakID = default(int);
				}
				this.SendPropertyChanged("Vak");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudent")]
public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_studentID;
	
	private string _studentNaam;
	
	private string _studentVoornaam;
	
	private string _studentPasswoord;
	
	private string _studentNummer;
	
	private int _fk_opleidingID;
	
	private EntitySet<Evk> _tblEvks;
	
	private EntityRef<Opleiding> _tblOpleiding;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_studentIDChanging(int value);
    partial void Onpk_studentIDChanged();
    partial void OnstudentNaamChanging(string value);
    partial void OnstudentNaamChanged();
    partial void OnstudentVoornaamChanging(string value);
    partial void OnstudentVoornaamChanged();
    partial void OnstudentPasswoordChanging(string value);
    partial void OnstudentPasswoordChanged();
    partial void OnstudentNummerChanging(string value);
    partial void OnstudentNummerChanged();
    partial void Onfk_opleidingIDChanging(int value);
    partial void Onfk_opleidingIDChanged();
    #endregion
	
	public Student()
	{
		this._tblEvks = new EntitySet<Evk>(new Action<Evk>(this.attach_tblEvks), new Action<Evk>(this.detach_tblEvks));
		this._tblOpleiding = default(EntityRef<Opleiding>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_studentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_studentID
	{
		get
		{
			return this._pk_studentID;
		}
		set
		{
			if ((this._pk_studentID != value))
			{
				this.Onpk_studentIDChanging(value);
				this.SendPropertyChanging();
				this._pk_studentID = value;
				this.SendPropertyChanged("pk_studentID");
				this.Onpk_studentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentNaam
	{
		get
		{
			return this._studentNaam;
		}
		set
		{
			if ((this._studentNaam != value))
			{
				this.OnstudentNaamChanging(value);
				this.SendPropertyChanging();
				this._studentNaam = value;
				this.SendPropertyChanged("studentNaam");
				this.OnstudentNaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentVoornaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentVoornaam
	{
		get
		{
			return this._studentVoornaam;
		}
		set
		{
			if ((this._studentVoornaam != value))
			{
				this.OnstudentVoornaamChanging(value);
				this.SendPropertyChanging();
				this._studentVoornaam = value;
				this.SendPropertyChanged("studentVoornaam");
				this.OnstudentVoornaamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentPasswoord", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentPasswoord
	{
		get
		{
			return this._studentPasswoord;
		}
		set
		{
			if ((this._studentPasswoord != value))
			{
				this.OnstudentPasswoordChanging(value);
				this.SendPropertyChanging();
				this._studentPasswoord = value;
				this.SendPropertyChanged("studentPasswoord");
				this.OnstudentPasswoordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNummer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentNummer
	{
		get
		{
			return this._studentNummer;
		}
		set
		{
			if ((this._studentNummer != value))
			{
				this.OnstudentNummerChanging(value);
				this.SendPropertyChanging();
				this._studentNummer = value;
				this.SendPropertyChanged("studentNummer");
				this.OnstudentNummerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_opleidingID", DbType="Int NOT NULL")]
	public int fk_opleidingID
	{
		get
		{
			return this._fk_opleidingID;
		}
		set
		{
			if ((this._fk_opleidingID != value))
			{
				if (this._tblOpleiding.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_opleidingIDChanging(value);
				this.SendPropertyChanging();
				this._fk_opleidingID = value;
				this.SendPropertyChanged("fk_opleidingID");
				this.Onfk_opleidingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblEvk", Storage="_tblEvks", ThisKey="pk_studentID", OtherKey="fk_studentID")]
	public EntitySet<Evk> Evks
	{
		get
		{
			return this._tblEvks;
		}
		set
		{
			this._tblEvks.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblStudent", Storage="_tblOpleiding", ThisKey="fk_opleidingID", OtherKey="pk_opleidingID", IsForeignKey=true)]
	public Opleiding Opleiding
	{
		get
		{
			return this._tblOpleiding.Entity;
		}
		set
		{
			Opleiding previousValue = this._tblOpleiding.Entity;
			if (((previousValue != value) 
						|| (this._tblOpleiding.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblOpleiding.Entity = null;
					previousValue.Students.Remove(this);
				}
				this._tblOpleiding.Entity = value;
				if ((value != null))
				{
					value.Students.Add(this);
					this._fk_opleidingID = value.pk_opleidingID;
				}
				else
				{
					this._fk_opleidingID = default(int);
				}
				this.SendPropertyChanged("Opleiding");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblEvks(Evk entity)
	{
		this.SendPropertyChanging();
		entity.Student = this;
	}
	
	private void detach_tblEvks(Evk entity)
	{
		this.SendPropertyChanging();
		entity.Student = null;
	}
}
#pragma warning restore 1591
