<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="dc_databankDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblBijlage" Member="Bijlages">
    <Type Name="Bijlage">
      <Column Name="pk_bijlageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bijlageURL" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="bijlageTitel" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="bijlageType" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fk_externvakID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblExternVak_tblBijlage" Member="ExternVak" Storage="_tblExternVak" ThisKey="fk_externvakID" OtherKey="pk_externvakID" Type="ExternVak" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblVak" Member="Vaks">
    <Type Name="Vak">
      <Column Name="pk_vakID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vakNaam" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="vakStudiepunten" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblVak_tblDocentVak" Member="DocentVaks" Storage="_tblDocentVaks" ThisKey="pk_vakID" OtherKey="fk_vakID" Type="DocentVak" />
      <Association Name="tblVak_tblEvk" Member="Evks" Storage="_tblEvks" ThisKey="pk_vakID" OtherKey="fk_vakID" Type="Evk" />
      <Association Name="tblVak_tblOpleidingVak" Member="OpleidingVaks" Storage="_tblOpleidingVaks" ThisKey="pk_vakID" OtherKey="fk_vakID" Type="OpleidingVak" />
    </Type>
  </Table>
  <Table Name="dbo.tblDocent" Member="Docents">
    <Type Name="Docent">
      <Column Name="pk_docentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="docentNaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="docentWachtwoord" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="docentAdmin" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="tblDocent_tblDocentVak" Member="DocentVaks" Storage="_tblDocentVaks" ThisKey="pk_docentID" OtherKey="fk_docentID" Type="DocentVak" />
    </Type>
  </Table>
  <Table Name="dbo.tblDocentVak" Member="DocentVaks">
    <Type Name="DocentVak">
      <Column Name="pk_docentvakID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_vakID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_docentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblDocent_tblDocentVak" Member="Docent" Storage="_tblDocent" ThisKey="fk_docentID" OtherKey="pk_docentID" Type="Docent" IsForeignKey="true" />
      <Association Name="tblVak_tblDocentVak" Member="Vak" Storage="_tblVak" ThisKey="fk_vakID" OtherKey="pk_vakID" Type="Vak" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblEvk" Member="Evks">
    <Type Name="Evk">
      <Column Name="pk_evkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_vakID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_externvakID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="evkDocentGoedgekeurd" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="evkAdminGoedgekeurd" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="tblVak_tblEvk" Member="Vak" Storage="_tblVak" ThisKey="fk_vakID" OtherKey="pk_vakID" Type="Vak" IsForeignKey="true" />
      <Association Name="tblExternVak_tblEvk" Member="ExternVak" Storage="_tblExternVak" ThisKey="fk_externvakID" OtherKey="pk_externvakID" Type="ExternVak" IsForeignKey="true" />
      <Association Name="tblStudent_tblEvk" Member="Student" Storage="_tblStudent" ThisKey="fk_studentID" OtherKey="pk_studentID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblExternVak" Member="ExternVaks">
    <Type Name="ExternVak">
      <Column Name="pk_externvakID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="externvakNaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="externvakStudiepunt" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="externvakJaar" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="externvakOpleiding" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="externvakSchool" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tblExternVak_tblBijlage" Member="Bijlages" Storage="_tblBijlages" ThisKey="pk_externvakID" OtherKey="fk_externvakID" Type="Bijlage" />
      <Association Name="tblExternVak_tblEvk" Member="Evks" Storage="_tblEvks" ThisKey="pk_externvakID" OtherKey="fk_externvakID" Type="Evk" />
    </Type>
  </Table>
  <Table Name="dbo.tblOpleiding" Member="Opleidings">
    <Type Name="Opleiding">
      <Column Name="pk_opleidingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="opleidingNaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tblOpleiding_tblOpleidingVak" Member="OpleidingVaks" Storage="_tblOpleidingVaks" ThisKey="pk_opleidingID" OtherKey="fk_opleidingID" Type="OpleidingVak" />
      <Association Name="tblOpleiding_tblStudent" Member="Students" Storage="_tblStudents" ThisKey="pk_opleidingID" OtherKey="fk_opleidingID" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.tblOpleidingVak" Member="OpleidingVaks">
    <Type Name="OpleidingVak">
      <Column Name="pk_opleidingvakID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_opleidingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_vakID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblOpleiding_tblOpleidingVak" Member="Opleiding" Storage="_tblOpleiding" ThisKey="fk_opleidingID" OtherKey="pk_opleidingID" Type="Opleiding" IsForeignKey="true" />
      <Association Name="tblVak_tblOpleidingVak" Member="Vak" Storage="_tblVak" ThisKey="fk_vakID" OtherKey="pk_vakID" Type="Vak" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblStudent" Member="Students">
    <Type Name="Student">
      <Column Name="pk_studentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentNaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studentVoornaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studentPasswoord" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studentNummer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fk_opleidingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblStudent_tblEvk" Member="Evks" Storage="_tblEvks" ThisKey="pk_studentID" OtherKey="fk_studentID" Type="Evk" />
      <Association Name="tblOpleiding_tblStudent" Member="Opleiding" Storage="_tblOpleiding" ThisKey="fk_opleidingID" OtherKey="pk_opleidingID" Type="Opleiding" IsForeignKey="true" />
    </Type>
  </Table>
</Database>